
package calculator.client.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 *
 */
@WebServiceClient(name = "StatefulCalculatorService", targetNamespace = "http://service.calculator/", wsdlLocation = "http://localhost:8080/services/calculator?wsdl")
public class StatefulCalculatorService
	extends Service
{

	private final static URL STATEFULCALCULATORSERVICE_WSDL_LOCATION;

	static {
		URL url = null;
		try {
			url = new URL("http://localhost:8080/services/calculator?wsdl");
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		STATEFULCALCULATORSERVICE_WSDL_LOCATION = url;
	}

	public StatefulCalculatorService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public StatefulCalculatorService() {
		super(STATEFULCALCULATORSERVICE_WSDL_LOCATION, new QName("http://service.calculator/", "StatefulCalculatorService"));
	}

	/**
	 *
	 * @return
	 *	 returns StatefulCalculator
	 */
	@WebEndpoint(name = "StatefulCalculatorPort")
	public StatefulCalculator getStatefulCalculatorPort() {
		return (StatefulCalculator)super.getPort(new QName("http://service.calculator/", "StatefulCalculatorPort"), StatefulCalculator.class);
	}

}
