
package calendar.client.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 *
 */
@WebServiceClient(name = "HebCalendarService", targetNamespace = "http://service.calendar/", wsdlLocation = "http://localhost:8080/services/hebcalendar?wsdl")
public class HebCalendarService
    extends Service
{

    private final static URL HEBCALENDARSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/hebcalendar?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HEBCALENDARSERVICE_WSDL_LOCATION = url;
    }

    public HebCalendarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HebCalendarService() {
        super(HEBCALENDARSERVICE_WSDL_LOCATION, new QName("http://service.calendar/", "HebCalendarService"));
    }

    /**
     *
     * @return
     *     returns HebCalendar
     */
    @WebEndpoint(name = "HebCalendarPort")
    public HebCalendar getHebCalendarPort() {
        return (HebCalendar)super.getPort(new QName("http://service.calendar/", "HebCalendarPort"), HebCalendar.class);
    }

}
