
package addressbook.client.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0_01-b59-fcs Generated
 * source version: 2.0
 */
@WebServiceClient(name = "AddressBookService", targetNamespace = "http://service.addressbook/", wsdlLocation = "http://localhost:8080/services/addressbook?wsdl")
public class AddressBookService extends Service {
	private static final URL ADDRESSBOOKSERVICE_WSDL_LOCATION;

	static {
		URL url = null;
		try {
			url = new URL("http://localhost:8080/services/addressbook?wsdl");
		} catch (MalformedURLException e) {
			throw new RuntimeException(e);
		}
		ADDRESSBOOKSERVICE_WSDL_LOCATION = url;
	}

	public AddressBookService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AddressBookService() {
		super(ADDRESSBOOKSERVICE_WSDL_LOCATION,
				new QName("http://service.addressbook/", "AddressBookService"));
	}

	/**
	 * @return returns AddressBook
	 */
	@WebEndpoint(name = "AddressBookPort")
	public AddressBook getAddressBookPort() {
		return (AddressBook) super.getPort(
				new QName("http://service.addressbook/", "AddressBookPort"),
				AddressBook.class);
	}

}
