package swing.advanced_swing;

import java.awt.EventQueue;
import java.util.regex.Pattern;

import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.WindowConstants;

@SuppressWarnings("serial")
public class DateForm extends JFrame {
	/** Creates new form dateForm */
	public DateForm() {
		initComponents();

		PlainDocument p = new PlainDocument() {
			private Pattern p = Pattern.compile("^\\d{4}-\\d{2}-\\d{2}$");

			private boolean check(String proposed) {
				if (p.matcher(proposed).find()) {
					System.out.println("match for " + proposed);
					return true;
				} else {
					System.out.println("no match for " + proposed);
					return false;
				}
			}

			@Override
			public void insertString(int offs, String str, AttributeSet a)
					throws BadLocationException {
				if (getLength() != 0) {
					String proposed = getText(0, offs) + str
							+ getText(offs + str.length(),
									getLength() - offs - str.length());
					if (check(proposed)) {
						super.remove(offs, str.length());
						super.insertString(offs, str, a);
						if (offs == 3 || offs == 6) {
							jTextField1.setCaretPosition(offs + 2);
						}
					}
				} else {
					super.insertString(offs, str, a);
				}

			}

			@Override
			public void remove(int offs, int len) throws BadLocationException {
				String proposed = getText(0, offs)
						+ getText(offs + len, getLength() - offs - len);
				if (check(proposed)) {
					super.remove(offs, len);
				}
			}

		};
		jTextField1.setDocument(p);
		jTextField1.setText("0000-00-00");
		jTextField1.setCaretPosition(0);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jTextField1 = new JTextField();
		jLabel1 = new JLabel();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jTextField1.setText("jTextField1");

		jLabel1.setText("Please enter your birthdate");

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(46, 46, 46)
						.addComponent(jLabel1).addGap(18, 18, 18)
						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE,
								176, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(33, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(73, 73, 73)
						.addGroup(layout
								.createParallelGroup(
										GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField1,
										GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addContainerGap(202, Short.MAX_VALUE)));

		pack();
	} // </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DateForm().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JLabel jLabel1;
	private JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}
