package swing.advanced_swing;

import javax.swing.JFrame;
import javax.swing.JCheckBox;
import javax.swing.JToolBar;
import javax.swing.JRadioButton;
import javax.swing.WindowConstants;
import javax.swing.SwingConstants;

@SuppressWarnings("serial")
public class MainFrame extends JFrame {

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jCheckBox1 = new JCheckBox();
		jCheckBox2 = new JCheckBox();
		jToolBar1 = new JToolBar();
		jRadioButton1 = new JRadioButton();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jCheckBox1.setText("jCheckBox1");

		jCheckBox2.setModel(jCheckBox1.getModel());
		jCheckBox2.setText("jCheckBox2");

		jToolBar1.setRollover(true);

		jRadioButton1.setModel(jCheckBox1.getModel());
		jRadioButton1.setText("jRadioButton1");
		jRadioButton1.setFocusable(false);
		jRadioButton1.setHorizontalTextPosition(SwingConstants.CENTER);
		jRadioButton1.setVerticalTextPosition(SwingConstants.BOTTOM);
		jToolBar1.add(jRadioButton1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(67, 67,
																		67)
																.addComponent(
																		jCheckBox1)
																.addGap(46, 46,
																		46)
																.addComponent(
																		jCheckBox2))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jToolBar1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		332,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(56, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(jToolBar1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										45,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										150, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jCheckBox1)
												.addComponent(jCheckBox2))
								.addGap(83, 83, 83)));

		pack();
	} // </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JCheckBox jCheckBox1;
	private JCheckBox jCheckBox2;
	private JRadioButton jRadioButton1;
	private JToolBar jToolBar1;
	// End of variables declaration//GEN-END:variables

}
