CREATE TABLE BOOKS (TITLE VARCHAR(250) PRIMARY KEY NOT NULL,AUTHOR VARCHAR(250),PRICE DOUBLE precision);
CREATE TABLE CUSTOMERS (ID VARCHAR(250)  PRIMARY KEY NOT NULL,NAME VARCHAR(250) NOT NULL,EMAIL VARCHAR(250) NOT NULL,ADDRESS VARCHAR(250) NOT NULL);
CREATE TABLE ORDERS (ID VARCHAR(250) PRIMARY KEY NOT NULL,ORDER_TIME BIGINT,CUSTOMER_ID VARCHAR(250) NOT NULL);
CREATE TABLE ORDER_ITEMS (ORDER_ID VARCHAR(250) NOT NULL,BOOK_TITLE VARCHAR(250) NOT NULL);