 CREATE TABLE `CUSTOMERS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`NAME` VARCHAR( 100 ) NOT NULL ,
	`EMAIL` VARCHAR( 100 ) NOT NULL ,
	`ADDRESS` VARCHAR( 200 ) NOT NULL
);

CREATE TABLE `BOOKS` (
	`TITLE` VARCHAR( 100 ) NOT NULL PRIMARY KEY,
	`AUTHOR` VARCHAR( 100 ) NOT NULL ,
	`PRICE` INT NOT NULL
) ;
